site_name: req_Canva_2024.1

repo_name: "req_Canva_2024.1"

repo_url: https://github.com/LuizaMaluf/req_Canva_2024.1

nav:
  - Home: index.md

theme:
    name: material
    nav_style: dark
    language: pt

    font:
        text: Roboto Mono 
    
    features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest  
    plugins:
        - typeset
        - search
    palette:
        - scheme: slate
          primary: black
          accent: light blue
          toggle:
                icon: material/weather-night
                name: Trocar para modo claro
        
        - scheme: default
          primary: blue grey
          accent: light blue
          toggle:
                icon: material/weather-sunny
                name: Trocar para modo escuro


markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde