site_name: Canva - Requisitos de Software

repo_name: "req_Canva_2024.1"
repo_url: https://github.com/LuizaMaluf/req_Canva_2024.1

nav:
  - Início: index.md
  - Pre-Rastreabilidade:
    - Rich Pictures: rich_picture.md
    - Argumentação: argumentacao.md
  - Elicitação:
    - Brainstorming: brainstorming.md
    - MoSCoW: moscow.md
    - First Things First: first_things.md
    - Análise de Protocolo: analise_protocolo.md
  - Reuniões:
    - Reunião 1: reuniao1.md
    - Reunião 2: reuniao2.md
    - Reunião 3: reuniao3.md

theme:
  name: material
  language: pt
  logo: images/logoCanva.png

  font:
    text: "Open Sans"
    code: "Source Code Pro"

  palette:
      primary: white

  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest

  extra_css:
    - stylesheets/custom.css

  plugins:
    - search
    - typeset

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
