site_name: Canva - Requisitos de Software

repo_name: 'req_Canva_2024.1'
repo_url: https://github.com/LuizaMaluf/req_Canva_2024.1

nav:
  - Início: index.md
  - Pre-Rastreabilidade:
    - Rich Pictures: pre-rastreabilidade/rich_picture.md
    - Argumentação: pre-rastreabilidade/argumentacao.md
  - Elicitação:
    - Brainstorming: elicitacao/brainstorming.md
    - MoSCoW: analise/correcoes/moscow_corrigido.md
    - First Things First: elicitacao/first_things.md
    - Análise de Protocolo: elicitacao/analise_protocolo.md
  - Modelagem:
    - Léxicos: modelagem/lexico.md
    - Cenários: modelagem/cenarios.md
    - Especificação de Casos de Uso: modelagem/casos_de_uso.md
    - Backlog do Produto e Histórias de Usuários: modelagem/backlog.md
    - Especificação Suplementar: analise/correcoes/esp_suplementar_corrigido.md
    - iStar: modelagem/istar.md
    - NFR Framework: modelagem/nfr-framework.md
  - Análise:
    - Validação da Argumentação: analise/verf_argumentacao.md
    - Validação da Priorização: analise/verf_priorizacao.md
    - Validação da Especificação Suplementar: analise/verf_esp_suplementar.md
  
  - Reuniões:
    - Reunião 1: atas/reuniao1.md
    - Reunião 2: atas/reuniao2.md
    - Reunião 3: atas/reuniao3.md
    - Reunião 4: atas/reuniao4.md
    - Reunião 5: atas/reuniao5.md
  - Entregas:
    - Entrega 1: entregas/entrega1.md
    - Entrega 2: entregas/entrega2.md

theme:
  name: material
  language: pt
  logo: images/logoCanva.png

  font:
    text: "Open Sans"
    code: "Source Code Pro"

  palette:
      primary: white

  features:
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest


  extra_css:
    - stylesheets/custom.css

  plugins:
    - search
    - typeset
    - nav-extensions

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
